# Generated by Django 4.2.10 on 2024-04-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tipo_Transacciones',
            new_name='Transaccion',
        ),
    ]
