# Generated by Django 4.2.10 on 2024-04-27 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tipo_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente_producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='tipo_transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='tipo_transaccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 59, 2, 386199)),
        ),
    ]
