# Generated by Django 4.2.10 on 2024-04-27 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_citie_created_at_alter_citie_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='citie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='countrie',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='countrie',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='identification_types',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 0, 8, 24, 412083)),
        ),
    ]
